# R �p�b�P�[�W�̃_�E�����[�h���̃~���[�T�C�g��ݒ�i�����ɌŒ�j
options(repos = structure(c(CRAN = "http://cran.ism.ac.jp/")))
Sys.setenv(RETICULATE_PYTHON = "C:\\Users\\honeycrack7\\AppData\\Local\\Programs\\Python\\Python36")

library("blogdown")
options(blogdown.ext = '.Rmd')
library("caret")
library("chron")
library("corrr")
library("data.table")
library("dplyr")
library("DT")
library("fasttime")
library("fPortfolio")
library("GGally")
library("ggExtra")
library("ggplot2")
library("ggrepel")
library("httr")
library("igraph")
library("lubridate")
library("magrittr")
library("networkD3")
library("openxlsx")
library("plotly")
library("psych")
library("qgraph")
library("quantmod")
library("reshape2")
library("RFinanceYJ")
library("reticulate")
library("stringr")
library("tcltk")
library("tidyr")
library("timeSeries")
library("xts")
