baseurl = "https://honeycrack7.github.io/asset/"
DefaultContentLanguage = "ja"

languageCode = "ja-jp"
hasCJKLanguage = true

publishDir = "docs"
relativeurls = true
canonifyurls = true

title = "A Hugo website"
# theme = "hugo-lithium"
theme = "hugo-theme-minos"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

toc = false
totop = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

#[[menu.main]]
#    name = "About"
#    url = "/about/"
#[[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/rstudio/blogdown"
#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/rstudio"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    smartToc = true
    katex = true
