---
title: VIXとVIX(CFD)
author: ~
date: '2020-03-28'
slug: vix-vixcfd
categories: []
tags: []
Categories:
  - 資産運用
Description: ''
Tags:
  - VIX
menu: ''
---

```{r echo=FALSE, include=FALSE}
# 前処理
vix <- getSymbols("^VIX",src="yahoo", from="1900-01-03", to=Sys.Date(), auto.assign=FALSE)
vix <- data.frame(index(vix),coredata(vix))
colnames(vix) <- c("date","open","high","low","vix","volume","adjusted")
write.csv(vix,file = "c:\\tmp\\data\\VIX\\VIX.csv",row.names = F)

vix_cfd <- read.csv("c:\\tmp\\data\\vix_cfd\\vix_cfd.csv")
# vix_cfd$date <- as.POSIXlt(vix_cfd$date)
vix_cfd$date <- as.POSIXct(vix_cfd$date)

# vix cfdを分足から日足に変換する
# 区切りが8：00~翌6：14かもしれないけど日付だけで計算する

vix_cfd <- vix_cfd %>%
  group_by(date(vix_cfd$date)) %>%
  do(tail(., 1))
vix_cfd <- vix_cfd[,c(6,5)]
colnames(vix_cfd) <- c("date", "vix_cfd")

# マージ
tmp1 <- merge(vix[,c(1,5)], vix_cfd[,c(1,2)], by.y = "date")
tmp2 <- melt(tmp1, id.vars = c("date"))
```

```{r}
datatable(tmp1,
        filter = 'top',
        style = 'bootstrap',
        class = 'table-bordered table-condensed',
#        class = 'cell-border stripe',
        extensions = 'ColReorder',
        options = list(dom = 'Rlfrtip',
                       colReorder = list(realtime = TRUE),
                       buttons = I('colvis'),
                       scrollX = TRUE,
                       scrollCollapse = TRUE
                       )
        )

ggplotly(
  ggplot(tmp2, aes(x = date, y = value, color = variable)) +
    geom_line()
)
```

```{r}
cor(tmp1[,c(2,3)])
```
相関は強いのでOK