---
title: "zandaka"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: yes
    theme: journal
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    code_folding: hide
    md_extensions: -ascii_identifiers
    includes:
      in_header: include_lightbox.html
---

# 前処理
```{r echo=FALSE, include=FALSE}
knitr::opts_chunk$set(comment='', message=FALSE, warning=FALSE, error=FALSE, 
                      eval=TRUE, echo=TRUE, include=TRUE)

options(scipen=1)

daily1 <- read.table('C:\\tmp\\data\\ETF\\etf_daily.csv',sep=",",header=T)
daily1$date <- as.Date(daily1$date)

zandaka <- read.table('C:\\tmp\\data\\ETF\\zandaka.csv',sep=",", header=T)
zandaka$date <- as.Date(zandaka$date)
zandaka_ticker <- c(t(zandaka$ticker))
zandaka$ticker <- as.factor(zandaka$ticker)

```

# グラフ描画 {.tabset .tabset-fade}

- max_draqdown（リーマンショックの経験から50％とする）
- under2σ（日次リターン過去1年分の）
- over2σ（日次リターン過去1年分の）

## 2510
```{r}
tarTicker <- c("2510")
data1 <- daily1 %>%
  filter(ticker == tarTicker) %>%
  tail(., 300) %>%
  mutate(return = close / dplyr::lag(close) - 1)
max_drawdown <- tail(data1$close, 1) * 0.5
under2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.02275)))
over2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.97725)))
tail(data)


g <- ggplot(NULL) +
  geom_line(data = data1, aes(x = date, y = close, colour = ticker)) +
  geom_point(data = subset(zandaka, ticker == tarTicker), aes(x = date, y = tanka, colour = ticker)) +
  geom_hline(yintercept = max_drawdown, linetype = "dashed", colour = "blue") +
  annotate("text", label = "max_drawdown", x = min(data1$date), y = max_drawdown + 10, 
           colour = "blue") + 
  geom_hline(yintercept = under2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "-2σ", x = min(data1$date), y = under2sigma - 20,
           colour = "blue") + 
  geom_hline(yintercept = over2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "+2σ", x = min(data1$date), y = over2sigma + 20,
           colour = "blue") + 
  annotate("text", label = round(tail(data1$close, 1) / zandaka[zandaka$ticker == tarTicker, 2] - 1,
                                 digits = 3),
           x = max(data1$date) + 5, y = tail(data1$close, 1) + 30, colour = "blue")

ggplotly(g)
```

## 2559
```{r}
tarTicker <- c("2559")
data1 <- daily1 %>%
  filter(ticker == tarTicker) %>%
  tail(., 300) %>%
  mutate(return = close / dplyr::lag(close) - 1)
max_drawdown <- tail(data1$close, 1) * 0.5
under2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.02275)))
over2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.97725)))
tail(data)


g <- ggplot(NULL) +
  geom_line(data = data1, aes(x = date, y = close, colour = ticker)) +
  geom_point(data = subset(zandaka, ticker == tarTicker), aes(x = date, y = tanka, colour = ticker)) +
  geom_hline(yintercept = max_drawdown, linetype = "dashed", colour = "blue") +
  annotate("text", label = "max_drawdown", x = min(data1$date), y = max_drawdown + 10, 
           colour = "blue") + 
  geom_hline(yintercept = under2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "-2σ", x = min(data1$date), y = under2sigma - 20,
           colour = "blue") + 
  geom_hline(yintercept = over2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "+2σ", x = min(data1$date), y = over2sigma + 20,
           colour = "blue") + 
  annotate("text", label = round(tail(data1$close, 1) / zandaka[zandaka$ticker == tarTicker, 2] - 1,
                                 digits = 3),
           x = max(data1$date) + 5, y = tail(data1$close, 1) + 30, colour = "blue")

ggplotly(g)
```

## 1458
```{r}
tarTicker <- c("1458")
data1 <- daily1 %>%
  filter(ticker == tarTicker) %>%
  tail(., 300) %>%
  mutate(return = close / dplyr::lag(close) - 1)
max_drawdown <- tail(data1$close, 1) * 0.5
under2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.02275)))
over2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.97725)))
tail(data)


g <- ggplot(NULL) +
  geom_line(data = data1, aes(x = date, y = close, colour = ticker)) +
  geom_point(data = subset(zandaka, ticker == tarTicker), aes(x = date, y = tanka, colour = ticker)) +
  geom_hline(yintercept = max_drawdown, linetype = "dashed", colour = "blue") +
  annotate("text", label = "max_drawdown", x = min(data1$date), y = max_drawdown + 10, 
           colour = "blue") + 
  geom_hline(yintercept = under2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "-2σ", x = min(data1$date), y = under2sigma - 20,
           colour = "blue") + 
  geom_hline(yintercept = over2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "+2σ", x = min(data1$date), y = over2sigma + 20,
           colour = "blue") + 
  annotate("text", label = round(tail(data1$close, 1) / zandaka[zandaka$ticker == tarTicker, 2] - 1,
                                 digits = 3),
           x = max(data1$date) + 5, y = tail(data1$close, 1) + 30, colour = "blue")

ggplotly(g)
```

## 1459
```{r}
tarTicker <- c("1459")
data1 <- daily1 %>%
  filter(ticker == tarTicker) %>%
  tail(., 300) %>%
  mutate(return = close / dplyr::lag(close) - 1)
max_drawdown <- tail(data1$close, 1) * 0.5
under2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.02275)))
over2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.97725)))
tail(data)


g <- ggplot(NULL) +
  geom_line(data = data1, aes(x = date, y = close, colour = ticker)) +
  geom_point(data = subset(zandaka, ticker == tarTicker), aes(x = date, y = tanka, colour = ticker)) +
  geom_hline(yintercept = max_drawdown, linetype = "dashed", colour = "blue") +
  annotate("text", label = "max_drawdown", x = min(data1$date), y = max_drawdown + 10, 
           colour = "blue") + 
  geom_hline(yintercept = under2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "-2σ", x = min(data1$date), y = under2sigma - 20,
           colour = "blue") + 
  geom_hline(yintercept = over2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "+2σ", x = min(data1$date), y = over2sigma + 20,
           colour = "blue") + 
  annotate("text", label = round(tail(data1$close, 1) / zandaka[zandaka$ticker == tarTicker, 2] - 1,
                                 digits = 3),
           x = max(data1$date) + 5, y = tail(data1$close, 1) + 30, colour = "blue")

ggplotly(g)
```

## bitcoin
```{r}
tarTicker <- c("bitcoin")
data1 <- daily1 %>%
  filter(ticker == tarTicker) %>%
  tail(., 300) %>%
  mutate(return = close / dplyr::lag(close) - 1)
max_drawdown <- tail(data1$close, 1) * 0.5
under2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.02275)))
over2sigma <- tail(data1$close, 1) * (1 + quantile( na.omit(data1$return), c(0.97725)))
tail(data)


g <- ggplot(NULL) +
  geom_line(data = data1, aes(x = date, y = close, colour = ticker)) +
  geom_point(data = subset(zandaka, ticker == tarTicker), aes(x = date, y = tanka, colour = ticker)) +
  geom_hline(yintercept = max_drawdown, linetype = "dashed", colour = "blue") +
  annotate("text", label = "max_drawdown", x = min(data1$date), y = max_drawdown + 10, 
           colour = "blue") + 
  geom_hline(yintercept = under2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "-2σ", x = min(data1$date), y = under2sigma - 20,
           colour = "blue") + 
  geom_hline(yintercept = over2sigma, linetype = "dashed", colour = "blue") +
  annotate("text", label = "+2σ", x = min(data1$date), y = over2sigma + 20,
           colour = "blue") + 
  annotate("text", label = round(tail(data1$close, 1) / zandaka[zandaka$ticker == tarTicker, 2] - 1,
                                 digits = 3),
           x = max(data1$date) + 5, y = tail(data1$close, 1) + 30, colour = "blue")

ggplotly(g)
```